version: 2
sources:
  - name: source
    database: '{{target.catalog}}'
    schema: source
    tables:
      - name: fact_sales
      - name: fact_returns
      - name: dim_date
      - name: dim_store
      - name: dim_product
      - name: dim_customer




  - name: bronze
    database: '{{target.catalog}}'
    schema: bronze
    tables:
      - name: bronze_sales
      - name: bronze_returns
      - name: bronze_data
      - name: bronze_store
      - name: bronze_product
      - name: bronze_customer




  - name: gold
    database: '{{target.catalog}}'
    schema: gold
    tables:
      - name: daily_sales

      - name: mart_sales_monthly