version: 2
sources:
  - name: source
    database: dbt_prod
    schema: source
    tables:
      - name: fact_sales
      - name: fact_returns
      - name: dim_date
      - name: dim_store
      - name: dim_product
      - name: dim_customer




  - name: bronze
    database: dbt_prod
    schema: bronze
    tables:
      - name: bronze_sales
      - name: bronze_returns
      - name: bronze_data
      - name: bronze_store
      - name: bronze_product
      - name: bronze_customer



